FROM jenkins/ssh-agent:jdk17

USER root

# Instalacion de python y sus modulos
RUN apt-get update && apt-get install -y python3 python3-pip  python3-flask python3-flake8 python3-bandit python3-coverage python3-pytest stress git curl

# Instalar jMeter

ENV JMETER_VERSION 5.6.3
ENV JMETER_HOME /opt/jmeter
ENV PATH $JMETER_HOME/bin:$PATH

RUN curl -LO https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
    && tar -xvzf apache-jmeter-$JMETER_VERSION.tgz -C /opt \
    && mv /opt/apache-jmeter-$JMETER_VERSION $JMETER_HOME \
    && rm apache-jmeter-$JMETER_VERSION.tgz
