services:
  jenkins-controller:
    build:
      context: ./apps/jenkins-controller
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins
  jenkins-agent-1:
    build:
      context: ./apps/jenkins-agent
    container_name: jenkins-agent-1
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    depends_on:
      - jenkins-controller
    networks:
      - jenkins
 
  jenkins-agent-2:
    build:
      context: ./apps/jenkins-agent
    container_name: jenkins-agent-2
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    depends_on:
      - jenkins-controller
    networks:
      - jenkins
    deploy:
      resources:
        limits:
            cpus: '1.0' 
            memory: 2G 
        reservations:
          cpus: '0.5'
          memory: 1G 
# https://wiremock.org/docs/standalone/docker/
  wiremock:
    image: "wiremock/wiremock:latest"
    restart: always
    container_name: wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    networks:
      - jenkins
    volumes:
      - ../test/wiremock:/home/wiremock # aun que deberia ser mas bien un Copy en un dockerfile
volumes:
  jenkins_home:

networks:
  jenkins: