services:
  jenkins-controller:
    build:
      context: ./apps/jenkins-controller
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins
  jenkins-agent-1:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins-agent-1
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    depends_on:
      - jenkins-controller
    networks:
      - jenkins

  jenkins-agent-2:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins-agent-2
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    depends_on:
      - jenkins-controller
    networks:
      - jenkins
# https://wiremock.org/docs/standalone/docker/
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    networks:
      - jenkins
volumes:
  jenkins_home:

networks:
  jenkins: